DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS doctor_availability CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS disease_history CASCADE;
DROP TABLE IF EXISTS visit_history CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;


