server:
  port: 8087
  servlet:
    context-path: /medconnect


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/med_connect
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 5
      maximumPoolSize: 25
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    cleanDisabled: false


api:
  imgur:
    url: https://api.imgur.com/
    albumHash: "k04aa3S"
    clientID: 8ce1a67ee460abc
    clientSecret: 02ec0abcae41871653935fe303043d743085b33d
    accessToken: 426a4a2fbf05d0a61679d0bdddbcffb5fb020e8c
    refreshToken: 38a5fe5f69e4d67eee5d470245d1e2d864a1cf71




logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  #  springframework:
     # security: DEBUG