
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS VisitHistory;
DROP TABLE IF EXISTS DiseaseHistory;
DROP TABLE IF EXISTS Visit;
DROP TABLE IF EXISTS User_Role;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS AppUser;
DROP TABLE IF EXISTS Doctor;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS flyway_schema_history;
